### ISSUE TITLE
Error in connecting to fujitsu general AC

### ISSUE THREAD

**Issue by ryohorii** [banban525/echonetlite2mqtt#31]
Thanks for sharing this project.
I tried to connect to Fujitsu General air conditioner equipped with OP-J03D wifi connector.
Then, echonetlite2mqtt produced the following exception error, as attached.

[echonet2mqtt_log.txt](https://github.com/banban525/echonetlite2mqtt/files/13758455/echonet2mqtt_log.txt)

**Comment by banban525** [comment]
@ryohorii 

Thank you for your report.
This problem is probably caused by the property receive command's latency being too short.

"Property 9f" arrived while echonetlite2mqtt was waiting to receive "Property 9e".
"Property 9f" is requested in the previous command.

Unfortunately, waiting times cannot be changed in current version.
In the next version I will add an option to change the wait time, so please wait a little.

```
warn  [ECHONETLite][raw] error getNewNode: get 9f: exception 192.168.2.43 013001
warn  [ECHONETLite][raw] error getNewNode: get 9e: invalid reveive data 192.168.2.43 013001 {"9f":"1d80818283848588898a8b8c8d8f9397989d9e9fa0a3b0b1b3babbbeccf6"}
```

**Comment by banban525** [comment]
@ryohorii

I have released ver.3.1.0.
This version increases the command latency to 3 seconds.
You can also change the wait time with the ECHONET_COMMAND_TIMEOUT option (or --echonetCommandTimeout option).

Please try upgrading to ver.3.1.0.

**Comment by ryohorii** [comment]
Thank you very much. I will try it.

**Comment by banban525** [comment]
@ryohorii 

Thank you for your report.
I'm glad the new version works well.

This warning means that ECHONETLite2MQTT found a property that does not exist in the ECHONET Lite specification.
This is probably a manufacturer-specific property.

```
warn  ERROR: unknown property. propertyNo === f6 in id: fe00008a10313036383338433434374546, ip:192.168.2.50, eoj:013001
```
