### ISSUE TITLE
How to control Lixil Shelter with Lixil Assist 2

### ISSUE THREAD

**Issue by fghpdf** [banban525/echonetlite2mqtt#35]
## Awesome Project
Hello, thanks for your hard work! This an awesome project, I am using this project to control my ACs now.

I bought a Lixil Assist 2 to control my Lixil shelter, but I only can see the `nodeProfile` and `controller`.

How can I use it to control my shelters?

### Controller
```json
{
  "operationStatus": "true",
  "installationLocation": "00",
  "protocol": "00004d00",
  "id": "fe000025bc340025778b00000000000000",
  "faultStatus": "false",
  "manufacturer": "000025",
  "productCode": "4c532d323530000000000000"
}
```
### NodeProfile
```json
{
  "operatingStatus": "true",
  "version": "010d0100",
  "id": "fe000025bc340025778b00000000000000",
  "manufacturer(MC)": "000025",
  "productCode": "4c532d323530000000000000",
  "selfNodeInstances": "000001",
  "selfNodeClasses": 2,
  "selfNodeInstanceListS": {
    "numberOfInstances": 3,
    "instanceList": [
      "05ff01",
      "026301",
      "026302"
    ]
  },
  "selfNodeClassListS": {
    "numberOfClasses": 1,
    "classList": [
      "05ff"
    ]
  },
  "instanceListNotification": {
    "numberOfinstances": 3,
    "instanceList": [
      "05ff01",
      "026301",
      "026302"
    ]
  }
}
```

Hope you have a nice day.

**Comment by banban525** [comment]
@fghpdf 

This issue has been closed, but has the problem been resolved?

'026301' and '026302' mean 'electricRainDoor', so Lixil Assist 2 seems to be working properly.
EchonetLite2MQTT may have failed to detect 'electricRainDoor'.
If the problem is still not resolved, please send me a detailed log and I will look into it.

A detailed log can be downloaded from the bottom of the Logs page.

**Comment by fghpdf** [comment]
@banban525 Hello, thanks for your reply. I restarted the server and it could detect the devices now.

Thanks for your great project!
