### ISSUE TITLE
Air Conditioners Showing as `nodeProfile`

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#8]
I'm testing out `echonetlite2mqtt` to use in my home. I have a number of different echonetlite devices, including several air conditioners.

It seems like my air conditioners aren't being discovered as air conditioners, but instead as `nodeProfile` objects, and they never seem to update after being discovered. If I restart `echonetlite2mqtt`, some get discovered, but not all.

I have tried some other echonetlite software, and these air conditioners do get discovered as air conditioners. Is there perhaps a race somewhere? 

What logging and information can I provide you?

**Comment by aftertommy** [comment]
This is the list of properties for one of the air conditioners. Notice the `manufacturer(MC)` code of `8`, which is Daikin:

{
  "operatingStatus": "true",
  "version": "010c0100",
  "id": "fe0000089c50d148d05800000000000000",
  "faultDescription": 0,
  "manufacturer(MC)": "000008",
  "uid": "342d",
  "selfNodeInstances": "000001",
  "selfNodeClasses": 2,
  "selfNodeInstanceListS": {
    "numberOfInstances": 1,
    "instanceList": [
      "013001"
    ]
  },
  "selfNodeClassListS": {
    "numberOfClasses": 1,
    "classList": [
      "0130"
    ]
  }
}

**Comment by banban525** [comment]
@aftertommy 

Thank you for your report.
I reproduced it with my Daikin air conditioner.

But 3 months ago it was fine.
Maybe, a firmware update for the air conditioner may have changed its behavior.

In my environment, the cause was that the ID of the nodeProfile and the ID of the air conditioner were the same.

I will fix this issue in a few days.

Also, detailed logs are not output. I plan to add functionality.

**Comment by aftertommy** [comment]
Thank you! Please let me know if I can help with gathering more info.

**Comment by aftertommy** [comment]
I’m curious, because I’m still learning how this protocol works — are you saying that Daikin is reusing the `nodeProfile` `SEOJ ` value but sending  property codes for the air conditioner class? I’m trying to understand how sometimes these get identified as normal air conditioners (and I’m trying to make sure I understand how echonet lite works).

**Comment by banban525** [comment]
@aftertommy 

I fixed this issue.

If you are using docker, use latest or tag:v2.0.1 or newer.
If you're running on node.js, clone the latest code.

In v2.0.1, I changed the nodeProfile Id if the nodeProfile and the device Id are the same.
This will show both the device and the nodeProfile.

If your problem was not due to duplicate Ids, please download the logs at the bottom of the "Logs" page and send them to me.

**Comment by aftertommy** [comment]
it looks to be working. thank you so much! oh man im so glad you have no idea.
