### ISSUE TITLE
Some devices failing to discover

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#9]
I have 6 air conditioners in my house, and sometimes echonetlite2mqtt seems to only find 4-5 of them, but not all 6. It's not always the same units, either.

When I've run other utilities like EchonetScanner on my Mac or iPhone, all the units are discovered immediately.

These are the IP addresses of the air conditioners:
192.168.40.121
192.168.40.135
192.168.40.223
192.168.40.103
192.168.40.253
192.168.40.127

It appears that the first AC (192.168.40.121) is failing to be discovered. I have attached logs below.

[echonetlite2mqtt_logs_internalsStatus.zip](https://github.com/banban525/echonetlite2mqtt/files/11010250/echonetlite2mqtt_logs_internalsStatus.zip)

**Comment by aftertommy** [comment]
What's interesting is that this AC _does_ appear to be appearing in the logs?:

```json
  "192.168.40.121": {
    "0ef001": {
      "83": "fe0000089c50d14990e600000000000000",
      "89": "0000",
      "d6": "01013001",
      "9d": "0280d5",
      "9e": "01bf",
      "9f": "0d808283898a9d9e9fbfd3d4d6d7",
      "d3": "000001",
      "d4": "0002",
      "d7": "010130"
    },
    "013001": {
      "80": "31",
      "81": "00",
      "82": "00004a00",
      "83": "fe0000089c50d14990e600000000000000",
      "84": "0064",
      "85": "000823fc",
      "93": "41",
      "9d": "068081888fa0b0",
      "9e": "0b80818f93a0a3b0b3b4c1c4",
      "9f": "1880818283848588898a8f939d9e9fa0a3b0b3b4babbbec1c4",
      "8f": "42",
      "a0": "33",
      "b0": "42",
      "b3": "1a",
      "ba": "1e",
      "bb": "16"
    }
  }
```

**Comment by banban525** [comment]
@aftertommy 

Thank you for sending the log.

I don't know the cause, but I know what happened.
ECHONETLite2MQTT needs the following properties to find the device
* 9d : Status change announcement property map
* 9e : Set property map
* 9f : Get property map
* 83 : Identification number
* 8a : Manufacturer code

ECHONETLite2MQTT has not received "8a" from your air conditioner.

```

   "192.168.40.121": {
     "0ef001": {
       "83": "fe0000089c50d14990e600000000000000",
       "89": "0000",
       "d6": "01013001",
       "9d": "0280d5",
       "9e": "01bf",
       "9f": "0d808283898a9d9e9fbfd3d4d6d7",
       "d3": "000001",
       "d4": "0002",
       "d7": "010130"
     },
     "013001": {
       "80": "31",
       "81": "00",
       "82": "00004a00",
       "83": "fe0000089c50d14990e600000000000000",
       "84": "0064",
       "85": "000823fc",
       "93": "41",
       "9d": "068081888fa0b0",
       "9e": "0b80818f93a0a3b0b3b4c1c4",
       "9f": "1880818283848588898a8f939d9e9fa0a3b0b3b4babbbec1c4",
       "8f": "42",
       "a0": "33",
       "b0": "42",
       "b3": "1a",
       "ba": "1e",
       "bb": "16"
     }
   },
```

Therefore, ECHONETLite2MQTT could not find the device.
However, this air conditioner has property "8a" (Manufacturer code).
Property "9f" is a list of properties that the device has.
"8a" exists because this air conditioner has the following properties:

```
80,81,82,83,84,85,88,89,8a,8f,93,9d,9e,9f,a0,a3,b0,b3,b4,ba,bb,be,c1,c4
```


You said "sometimes not found", so perhaps it's a timing issue, failing to receive properties.

I came up with two solutions

(1) Change property receive interval

You can change the property receive interval with the environment variable `ECHONET_INTERVAL_TO_GET_PROPERTIES` (or `--echonetIntervalToGetProperties` option).
The default is 100, so changing it to (eg 200) might solve the problem.

This does not require program modification.

However, if you increase this value too much, ECHONETLite2MQTT will take longer to find the device for the first time.


(2) Add retry feature

I'm planning on adding a retry feature.
After ECHONETLite2MQTT receives some properties, if ECHONETLite2MQTT retries to receive properties, it may be able to find the device.
The retry feature is planned to be able to be executed manually or automatically.

However, this requires program modification, and you need to wait for about a week.

**Comment by aftertommy** [comment]
I can wait! Thank you for all of your help.

**Comment by aftertommy** [comment]
@banban525 since I know the IP addresses of the devices ahead of time, it would be great if I could refresh the information for these devices using the IP address.

Or, if that's not possible, it'd be great if I could trigger a refresh using the device ID.

For example, if I'm waiting for an air conditioner with device ID `fe0000089c50d148d05800000000000000` to be discovered by echonetlite2mqtt, it'd be great if I could trigger a refresh using a command topic like:

`echonetlite2mqtt/elapi/v2/devices/fe0000089c50d148d05800000000000000/refresh`

or

`echonetlite2mqtt/elapi/v2/devicesByIP/192.168.40.121/refresh`

**Comment by banban525** [comment]
@aftertommy 

Added auto-retry feature in v2.1.0.

This feature may solve your problem.

However, manual retry feature are deferred.
I plan to create a new page "system" or "maintenance" and add manual retry feature to that page.
I'll solve #11 first, because creating a new page takes time.

**Comment by aftertommy** [comment]
i’ll give it a shot! thank you!

**Comment by aftertommy** [comment]
I had initially tried this with the auto retry interval set to 200ms (I was using this value before updating to `2.1.0`), and it seemed like things were stalling after discovering the first few devices. I then reverted to 100ms, and after a bit it appears to have discovered everything on my network.

Thank you!
